name: lafan1
target_fps: 30
preprocess:
  min_frames: 22
  normalize_root_xy: true
  ground_align: none
  max_all_off_ground_s: 0.8
  off_ground_height: 0.12
sources:
  - name: lafan1
    type: bvh
    input: data/lafan1_bvh
    bvh_format: lafan1
    exclude_patterns:
      - "*obstacle*"
